# Generated by Django 4.2.10 on 2024-02-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=12)),
                ('mmse', models.IntegerField(default=0)),
                ('hippo', models.FloatField(default=0)),
                ('mri', models.ImageField(upload_to='manager/data')),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('birth', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=2)),
                ('smoking', models.BooleanField(default=False)),
                ('drinking', models.BooleanField(default=False)),
                ('depression', models.BooleanField(default=False)),
                ('specific', models.CharField(max_length=20)),
            ],
        ),
    ]
